# Site settings
title: 18MillionRising.org
email: info@18millionrising.org
description: > # this means to ignore newlines until "baseurl:"
  Activating Asian America
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://18millionrising.org" # the base hostname & protocol for your site
twitter_username: 18millionrising
facebook: https://facebook.com/18MillionRising.org
tumblr: http://18mr.tumblr.com
insta: http://instagram.com/18millionrising
github_username: 18mr
feature_banner: "/static/images/banners/votervox.png"

# Build settings
markdown: kramdown

# Output
permalink: /:year/:month/:title.html
paginate: 6
categories:
- ideas
- culture
- identities
- communities
collections:
- authors
- staff
- campaigns